"""create serializer rules for each model

Revision ID: 4ff85a67a3b8
Revises: 6487119713b5
Create Date: 2024-03-04 19:57:54.742226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff85a67a3b8'
down_revision = '6487119713b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
