"""create realtionships between models/tables

Revision ID: 6487119713b5
Revises: 800a8ac8f3fe
Create Date: 2024-03-04 19:29:03.934126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6487119713b5'
down_revision = '800a8ac8f3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('reading_log_id', sa.INTEGER(), nullable=True),
    sa.Column('favorite', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['reading_log_id'], ['reading_logs.id'], name='fk_user_logs_reading_log_id_reading_logs'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_logs_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
