"""create new user logs table

Revision ID: 800a8ac8f3fe
Revises: 998ef53d643c
Create Date: 2024-02-28 19:19:01.716371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800a8ac8f3fe'
down_revision = '998ef53d643c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reading_log_id', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reading_log_id'], ['reading_logs.id'], name=op.f('fk_user_logs_reading_log_id_reading_logs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_logs')
    # ### end Alembic commands ###
