"""create new books table

Revision ID: 8d544098ba9b
Revises: ac4eb311bebe
Create Date: 2024-02-27 18:38:59.994491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d544098ba9b'
down_revision = 'ac4eb311bebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
