"""add end date column in reading logs table

Revision ID: 998ef53d643c
Revises: 52436e05bc55
Create Date: 2024-02-28 19:04:58.451764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998ef53d643c'
down_revision = '52436e05bc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_logs', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_logs', 'end_date')
    # ### end Alembic commands ###
