"""fix typo in reading logs table

Revision ID: a971432f51f9
Revises: 7815f41bd379
Create Date: 2024-02-28 19:03:37.265127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a971432f51f9'
down_revision = '7815f41bd379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_logs', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('reading_logs', 'start_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_logs', sa.Column('start_data', sa.DATETIME(), nullable=True))
    op.drop_column('reading_logs', 'start_date')
    # ### end Alembic commands ###
