"""create new users table

Revision ID: ac4eb311bebe
Revises: 9b2a0d5d1e9e
Create Date: 2024-02-27 18:38:29.309885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4eb311bebe'
down_revision = '9b2a0d5d1e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
