"""added password column to users table

Revision ID: b8c4d2a3dcb3
Revises: 4ff85a67a3b8
Create Date: 2024-03-04 20:05:17.547318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c4d2a3dcb3'
down_revision = '4ff85a67a3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password_hash')
    # ### end Alembic commands ###
